/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import validator.Validator;

/**
 *
 * @author Gazi
 */
public class PasswordInputField extends javax.swing.JPanel implements InputValue {

    private Validator validator;

    /**
     * Creates new form InputTextField
     */
    public PasswordInputField() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(600, 34));
        setMinimumSize(new java.awt.Dimension(600, 34));
        setPreferredSize(new java.awt.Dimension(600, 34));

        txtLabel.setText("Username:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setText(String text) {
        txtLabel.setText(text);
    }

    public void setValue(String text) {
        passwordField.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel txtLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getValue() throws Exception {
        if (validator != null) {
            try {
                validator.validate(passwordField.getText());
                passwordField.setBorder(UIManager.getBorder("TextField.border"));
                return passwordField.getText();
            } catch (Exception e) {
                passwordField.setBorder(BorderFactory.createLineBorder(Color.red, 1));
                throw e;
            }
        } else {
            return passwordField.getText();
        }
    }

}
